apiVersion: apps/v1
kind: Deployment                                  # Type of the kubernetes resource
metadata:
  name: fullstack-app-postgres                    # Name of the Kubernetes resource
  labels:
    app: fullstack-app-postgres
spec:
  replicas: 1                                     # Number of pods to run at any given time
  selector:
    matchLabels:
      app: fullstack-app-postgres                 # This deployment applies to any Pods matching the specified label
  template:                                       # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                                     # The labels that will be applied to all of the pods in this deployment
        app: fullstack-app-postgres
    spec:                                         # Spec for the container which will run in the Pod
      containers:
        - name: fullstack-app-postgres
          image: fullstack-postgres:latest       # The image we are getting from dockerhub
          imagePullPolicy: Never             # If we have not pulled it before, get it from dockerhub
          envFrom:
            - secretRef:
                name: postgres-secret
          command: [ "sh","-c","./main $FLAG $TEXT" ]
          env:
            - name: FLAG
              value: "-y"
        - name: sidecar-app
          image: fullstack-postgres:latest
          imagePullPolicy: Never
          envFrom:
            - secretRef:
                name: postgres-secret
          command: ["sh","-c","./main $FLAG $TEXT"]
          env:
            - name: FLAG
              value: "-c"