version: '3.3'
networks:
  fullstack:
    external: true
services:
  app:
    container_name: full_app
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - /:/usr/src/app/
    depends_on:
      - fullstack-postgres          # Uncomment this when using postgres.
    networks:
      - fullstack
  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    networks:
      - fullstack