apiVersion: batch/v1
kind: Job
metadata:
  name: kuber-test
spec:
  template:
    metadata:
      name: kuber-test
    spec:
      containers:
      - name: kuber-test
        image: fullstack-postgres:latest
        imagePullPolicy: Never
        command: ["sh","-c","./main $FLAG $TEXT"]
        env:
          - name: FLAG
            value: "-g"
        ports:
          - name: http
            containerPort: 8080                   # Should match the port number that the Go application listens on
        envFrom:
          - secretRef:
              name: postgres-secret

      restartPolicy: OnFailure